# Generated by Django 3.0.2 on 2020-01-29 02:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('Compact', 'Compact'), ('Luxury', 'Luxury'), ('SUV', 'SUV'), ('Sport', 'Sport')], default='Compact', max_length=150)),
                ('special_request', models.CharField(blank=True, max_length=150, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Wait for Driver to confirm'), (1, 'Sharer Joined'), (2, 'Confirmed by Driver'), (3, 'Complete')], default=0)),
                ('owner_count', models.IntegerField(default=0, verbose_name='Number of Passengers in your party')),
                ('is_shared', models.BooleanField(default=True, verbose_name='Share with others')),
                ('dest', models.CharField(default=None, max_length=150, verbose_name='Destination')),
                ('arrival_daytime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrival Time')),
                ('sharer_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Expected Vehicle Type')),
                ('special_request', models.CharField(blank=True, max_length=150, null=True, verbose_name='Any Special Request')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('psg', models.ManyToManyField(default=None, related_name='psg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
