# Generated by Django 3.0.2 on 2020-02-02 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='realname',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
