# Generated by Django 3.0.2 on 2020-02-02 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0002_auto_20200201_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='psg_count',
            field=models.IntegerField(default=0, verbose_name='Number of all passengers'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='psg',
            field=models.ManyToManyField(default=1, related_name='psg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('Compact', 'Compact'), ('Luxury', 'Luxury'), ('SUV', 'SUV'), ('Sport', 'Sport')], default='Compact', max_length=150, verbose_name='Expected Vehicle Type'),
        ),
    ]
