# Generated by Django 3.0.2 on 2020-02-01 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0002_auto_20200131_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='psg',
            field=models.ManyToManyField(default=1, related_name='psg', to=settings.AUTH_USER_MODEL),
        ),
    ]
