# Generated by Django 3.0.2 on 2020-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0003_auto_20200201_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacity except yourself'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_num',
            field=models.CharField(max_length=150, verbose_name='Plate number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='realname',
            field=models.CharField(default=None, max_length=150, verbose_name='Your real name'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='special_request',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Special request'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Compact', 'Compact'), ('Luxury', 'Luxury'), ('SUV', 'SUV'), ('Sport', 'Sport')], default='Compact', max_length=150, verbose_name='Vehicle type'),
        ),
    ]
