# Generated by Django 3.0.2 on 2020-02-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0004_auto_20200201_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacity (excluding yourself)'),
        ),
    ]
